using DoSomething;
using DoSomething.Properties;
using System;
using System.IO;
using System.Drawing;
using System.Windows.Forms;

namespace DoSomethingEx
{
    public partial class MainForm : Form
    {
        private readonly ApplicationStateManager _stateManager;
        private readonly MouseController _mouseController;
        private readonly MenuBuilder _menuBuilder;
        private readonly GlobalKeyboardHook _globalKeyboardHook;
        private readonly GlobalMouseHook _globalMouseHook;
        private TaskbarIconManager _taskbarIconManager;

        public MainForm()
        {
            InitializeComponent();

            // Initialize application components using dependency injection pattern
            _stateManager = new ApplicationStateManager();
            var movementStrategy = new HumanLikeMouseMovement();
            _mouseController = new MouseController(movementStrategy, _stateManager);
            _menuBuilder = new MenuBuilder(OnInIntervalSelected, OnAtTimeSelected);

            // Setup event handlers
            _stateManager.StateChanged += OnStateChanged;

            // Initialize global hooks
            _globalKeyboardHook = new GlobalKeyboardHook();
            _globalKeyboardHook.KeyboardPressed += OnKeyboardActivity;
            _globalKeyboardHook.Hook();

            _globalMouseHook = new GlobalMouseHook();
            _globalMouseHook.MouseMoved += OnMouseActivity;
            _globalMouseHook.Hook();
        }

        private void MainForm_Load(object sender, EventArgs e)
        {
            numStopAfter.Value = Settings.Default.LastTimeout;
            var appIcon = new Icon(File.OpenRead("appIcon.ico"));
            Icon = appIcon;

            // Initialize taskbar icon manager (requires window handle)
            _taskbarIconManager = new TaskbarIconManager(Handle);
            _taskbarIconManager.UpdateIcon(_stateManager.CurrentState);

            UpdateStatusLabel();
        }

        private void MainForm_FormClosing(object sender, FormClosingEventArgs e)
        {
            _globalKeyboardHook.Unhook();
            _globalMouseHook.Unhook();
            _taskbarIconManager?.Dispose();
        }

        #region Timer Events

        private void TmrWorker_Tick(object sender, EventArgs e)
        {
            _stateManager.IncrementIdleTime();
            _mouseController.ProcessTick();
            UpdateStatusLabel();
        }

        private void TmrStop_Tick(object sender, EventArgs e)
        {
            btnStartStop.PerformClick();
        }

        #endregion

        #region Input Detection

        private void OnKeyboardActivity(object sender, EventArgs e)
        {
            if (_stateManager.IsRunning)
            {
                _stateManager.Pause();
            }
        }

        private void OnMouseActivity(object sender, EventArgs e)
        {
            // Ignore mouse moves generated by our application
            if (_mouseController.ShouldIgnoreNextMouseMove)
            {
                return;
            }

            if (_stateManager.IsRunning && !_stateManager.IsPaused)
            {
                _stateManager.Pause();
            }
        }

        #endregion

        #region UI Event Handlers

        private void Button1_Click(object sender, EventArgs e)
        {
            int tag = Convert.ToInt32(btnStartStop.Tag);

            if (tag == 0) // Start
            {
                StartApplication();
            }
            else // Stop
            {
                StopApplication();
            }

            tag = 1 - tag;
            btnStartStop.Tag = tag;
            btnStartStop.Text = tag == 0 ? "Start" : "Stop";
        }

        private void contextMenuStrip1_Opening(object sender, System.ComponentModel.CancelEventArgs e)
        {
            _menuBuilder.BuildInMenu(inToolStripMenuItem);
            _menuBuilder.BuildAtMenu(atToolStripMenuItem);
        }

        #endregion

        #region Application Control

        private void StartApplication()
        {
            _mouseController.Initialize();
            _stateManager.Start();

            tmrWorker.Start();
            WindowState = FormWindowState.Minimized;

            var timeout = TimeSpan.FromMinutes((double)numStopAfter.Value);
            tmrStop.Interval = (int)timeout.TotalMilliseconds;
            tmrStop.Start();

            Settings.Default.LastTimeout = (int)numStopAfter.Value;
            Settings.Default.Save();
        }

        private void StopApplication()
        {
            tmrWorker.Stop();
            tmrStop.Stop();
            _stateManager.Stop();
            WindowState = FormWindowState.Normal;
        }

        #endregion

        #region Menu Callbacks

        private void OnInIntervalSelected(int minutes)
        {
            numStopAfter.Value = minutes;
        }

        private void OnAtTimeSelected(DateTime targetTime)
        {
            int minutes = (int)(targetTime - DateTime.Now).TotalMinutes;
            if (minutes < 1) minutes = 1;
            numStopAfter.Value = minutes;
        }

        #endregion

        #region State Management

        private void OnStateChanged(object sender, ApplicationState newState)
        {
            UpdateStatusLabel();
            _taskbarIconManager?.UpdateIcon(newState);
        }

        private void UpdateStatusLabel()
        {
            lblStatus.Text = _stateManager.GetStatusText();
        }

        #endregion
    }
}
